//SHOP TYPES
export const FETCH_CATALOGUE_START = "FETCH_CATALOGUE_START";
export const FETCH_CATALOGUE_SUCCESS = "FETCH_CATALOGUE_SUCCESS";
export const FETCH_CATALOGUE_FAILURE = "FETCH_CATALOGUE_FAILURE";

//CART TYPES
export const ADD_ITEM = "ADD_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_CART = "CLEAR_CART";
